#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configuration
ufw allow 'Nginx HTTP'

# Creating Sample Page
echo "Hello World!" | sudo tee /var/www/html/index.html

# add the following configuration to the existing server block
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
